options_request:
    path: /{request}
    controller: App\Controller\DefaultController::handleOptionsRequest
    methods: OPTIONS
    requirements:
        request: ".+"
        
controllers:
    resource: ../src/Controller/
    type: attribute

recipes:
    path: /recipes/
    controller: App\Controller\RecipeController::get
    methods: GET
recipe:
    path: /recipes/{id}
    controller: App\Controller\RecipeController::getByID
    methods: GET
recipe_create:
    path: /recipes
    controller: App\Controller\RecipeController::create
    methods: POST
recipe_update:
    path: /recipes/{id}
    controller: App\Controller\RecipeController::update
    methods: PUT 
recipe_delete:
    path: /recipes/{id}
    controller: App\Controller\RecipeController::delete
    methods: DELETE

users:
    path: /users
    controller: App\Controller\UserController::get
    methods: GET
user:
    path: /users/{id}
    controller: App\Controller\UserController::getByID
    methods: GET
user_create:
    path: /users
    controller: App\Controller\UserController::create
    methods: POST
user_update:
    path: /users/{id}
    controller: App\Controller\UserController::update
    methods: PUT 
user_delete:
    path: /users/{id}
    controller: App\Controller\UserController::delete
    methods: DELETE
user_getByEmail:
  path: /users/get-by-email
  controller: App\Controller\UserController::getByEmail
  methods: POST

ingredients:
    path: /ingredients
    controller: App\Controller\IngredientController::get
    methods: GET
ingredient:
    path: /ingredients/{id}
    controller: App\Controller\IngredientController::getByID
    methods: GET
ingredient_create:
    path: /ingredients
    controller: App\Controller\IngredientController::create
    methods: POST
ingredient_update:
    path: /ingredients/{id}
    controller: App\Controller\IngredientController::update
    methods: PUT 
ingredient_delete:
    path: /ingredients/{id}
    controller: App\Controller\IngredientController::delete
    methods: DELETE
